<?php // Important Note: save this file without formatting!!
declare/* comment */(ticks=1);
declare   (ticks=2);
declare(   ticks=3);
declare(TICKS  =4);
declare(ticks=   5);
declare(ticks=6   );
declare(ticks=7);
declare(tIcKs=8   )    ;
declare(ticks=9) /* comment */;
declare(/* comment */ ticks=10    )    ;
declare(/* comment */ ticks /* comment */ =11);


declare(
  ticks=12
);

declare(  ticks
=13   );


    declare(ticks=14) { }

  declare(ticks=15)
{ }


declare(ticks=16)
{

    }

declare(ticks=17) { }

declare(ticks=18) { }$x =1;

    declare(ticks=19) {
      $foo = false;
    }

declare(  ticks // phpcs:ignore Standard.Category.Sniff
=20);

declare(ticks=21) {
}$x =1; // phpcs:ignore Standard.Category.Sniff

declare(ticks=22) { // comment
}

declare(ticks=23) {$foo = false;
}

        declare(ticks=24) { /* comment */  /* comment */      $foo = false;
}

declare(ticks=25) {  $foo = false;
}

declare( ticks = 26 );

DECLARE( ticks = 27 );
DeClArE( ticks = 28 );
