<?php

// phpcs:set BigBite.Commenting.DocCommentLineLength absoluteLineLimit 90
// phpcs:set BigBite.Commenting.DocCommentLineLength includeIndentation true

                          /**
                           * This is a comment line that should trigger a warning.
                           */

                          /**
                           * This is a comment line that should trigger an error due to this config setting.
                           */

// phpcs:set BigBite.Commenting.DocCommentLineLength absoluteLineLimit 90
// phpcs:set BigBite.Commenting.DocCommentLineLength includeIndentation false
