<?php

/**
 * This is a comment line that exceeds 80 characters, and should therefore trigger a warning.
 */

/**
 * This is a comment line that exceeds the maximum 100 characters, and should therefore trigger an error.
 */

/**
 * This-comment-exceeds-80-characters-but-is-non-breakable-text-so-should-not-trigger-a-warning.
 */

/**
 * This-comment-line-exceeds-the-maximum-100-characters-but-is-non-breakable-text-so-should-not-trigger-an-error.
 */

/**
 * Plugin Name: Line lengths
 * Description: WordPress plugin/theme comment line lengths are excluded from this sniff.
 */

/**
 * Theme Name: Line lengths
 * Description: WordPress plugin/theme comment line lengths are excluded from this sniff, both soft limit and hard limit.
 */

/**
 * This is a comment line that should not trigger a warning, nor an error.
 */

                          /**
                          * This is a comment line that should not trigger a warning, nor an error.
                          */
